name: Validar que URLs de testing NO estén activas

on:
  push:
  pull_request:

jobs:
  verificar_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Buscar USOS de variables de TEST en WebServicesDeportnet.cs
        run: |
          ARCHIVO="AplicacionReconocimiento/DeportnetApi/Service/WebServicesDeportnet.cs"

          # Buscar nombres de variables con "Test" usados fuera de su declaración
          VARS_TEST=$(grep -hoP 'const string (\w+Test)' "$ARCHIVO" | awk '{print $3}' | sort | uniq)

          RET=0
          for VAR in $VARS_TEST; do
            if grep -w "$VAR" "$ARCHIVO" | grep -v "const string $VAR" ; then
              echo "::error ::ERROR: La variable de TEST '$VAR' está siendo utilizada en el código fuente."
              RET=1
            fi
          done

          # Buscar si la URL de testing es pasada directa
          if grep 'https://testing.deportnet.com' "$ARCHIVO" | grep -v "const string"; then
            echo "::error ::ERROR: Se está usando una URL de testing directamente en el código."
            RET=1
          fi

          exit $RET
